spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/finflow

  cloud:
    gateway:
      routes:
        - id: transaction-service
          uri: http://localhost:8081
          predicates:
            - Path=/transactions/**

        - id: wallet-service
          uri: http://localhost:8082
          predicates:
            - Path=/wallet/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true